version: "3.1"
services:

    mariadb:
      image: mariadb:10.2
      container_name: hacktalk-mariadb
      working_dir: /application
      volumes:
        - .:/application
        - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=vse_khorosho
      ports:
        - "3306:3306"

    webserver:
      image: nginx:alpine
      container_name: hacktalk-webserver
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "10001:80"
      depends_on:
        - php-fpm

    php-fpm:
      build: phpdocker/php-fpm
      container_name: hacktalk-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.0/fpm/conf.d/99-overrides.ini
      depends_on:
        - mariadb

